In [14]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [72]:
data = pd.read_csv('titanic.csv', index_col = 'PassengerId')

In [73]:
data['Sex'] = data['Sex'].replace('male', 1)
data['Sex'] = data['Sex'].replace('female', 0)

In [76]:
data = data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']]
data = data.dropna()
data

Pclass      Fare   Age  Sex  Survived
PassengerId                                       
1                 3    7.2500  22.0    1         0
2                 1   71.2833  38.0    0         1
3                 3    7.9250  26.0    0         1
4                 1   53.1000  35.0    0         1
5                 3    8.0500  35.0    1         0
7                 1   51.8625  54.0    1         0
8                 3   21.0750   2.0    1         0
9                 3   11.1333  27.0    0         1
10                2   30.0708  14.0    0         1
11                3   16.7000   4.0    0         1
12                1   26.5500  58.0    0         1
13                3    8.0500  20.0    1         0
14                3   31.2750  39.0    1         0
15                3    7.8542  14.0    0         0
16                2   16.0000  55.0    0         1
17                3   29.1250   2.0    1         0
19                3   18.0000  31.0    0         0
21                2   26.0000  35.0    1         0
22                2   13.0000  34.0    1         1
23                3    8.0292  15.0    0         1
24                1   35.5000  28.0    1         1
25                3   21.0750   8.0    0         0
26                3   31.3875  38.0    0         1
28                1  263.0000  19.0    1         0
31                1   27.7208  40.0    1         0
34                2   10.5000  66.0    1         0
35                1   82.1708  28.0    1         0
36                1   52.0000  42.0    1         0
38                3    8.0500  21.0    1         0
39                3   18.0000  18.0    0         0
...             ...       ...   ...  ...       ...
857               1  164.8667  45.0    0         1
858               1   26.5500  51.0    1         1
859               3   19.2583  24.0    0         1
861               3   14.1083  41.0    1         0
862               2   11.5000  21.0    1         0
863               1   25.9292  48.0    0         1
865               2   13.0000  24.0    1         0
866               2   13.0000  42.0    0         1
867               2   13.8583  27.0    0         1
868               1   50.4958  31.0    1         0
870               3   11.1333   4.0    1         1
871               3    7.8958  26.0    1         0
872               1   52.5542  47.0    0         1
873               1    5.0000  33.0    1         0
874               3    9.0000  47.0    1         0
875               2   24.0000  28.0    0         1
876               3    7.2250  15.0    0         1
877               3    9.8458  20.0    1         0
878               3    7.8958  19.0    1         0
880               1   83.1583  56.0    0         1
881               2   26.0000  25.0    0         1
882               3    7.8958  33.0    1         0
883               3   10.5167  22.0    0         0
884               2   10.5000  28.0    1         0
885               3    7.0500  25.0    1         0
886               3   29.1250  39.0    0         0
887               2   13.0000  27.0    1         0
888               1   30.0000  19.0    0         1
890               1   30.0000  26.0    1         1
891               3    7.7500  32.0    1         0

[714 rows x 5 columns]

In [77]:
X = data[['Pclass', 'Fare', 'Age', 'Sex']].values
X

array([[ 3.    ,  7.25  , 22.    ,  1.    ],
       [ 1.    , 71.2833, 38.    ,  0.    ],
       [ 3.    ,  7.925 , 26.    ,  0.    ],
       ...,
       [ 1.    , 30.    , 19.    ,  0.    ],
       [ 1.    , 30.    , 26.    ,  1.    ],
       [ 3.    ,  7.75  , 32.    ,  1.    ]])

In [78]:
y = data[['Survived']].values
y

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [79]:
clf = DecisionTreeClassifier(random_state=241)

In [80]:
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=241,
            splitter='best')

In [81]:
clf.feature_importances_

array([0.14000522, 0.30343647, 0.2560461 , 0.30051221])

In [82]:
['Pclass', 'Fare', 'Age', 'Sex']

['Pclass', 'Fare', 'Age', 'Sex']